/* Read-only operator workspace; never mutates the active policy. */
(async function () {
  const response = await fetch('/forge-summary.json');
  if (!response.ok) throw new Error('Research summary unavailable');
  const forge = await response.json();
  const style = document.createElement('style');
  style.textContent = `.forge{font-size:16px;line-height:1.6}.forge h2{font-size:24px;margin:0 0 12px}.forge h3{font-size:19px;margin:0 0 10px}.forge p{margin:8px 0 16px}.forge .f-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px;margin:20px 0}.forge .f-card{padding:22px;border:1px solid #36445d;border-radius:16px;background:#101a2b}.forge .f-hold{border-left:5px solid #fbbf24}.forge .f-badge{display:inline-block;padding:3px 10px;border-radius:6px;background:#233653;color:#bae6fd;font-size:14px;margin-bottom:10px}.forge .f-number{font-size:32px;font-weight:750;color:#8be5ed}.forge .f-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.forge button,.forge select,.forge input{font:inherit;padding:10px 14px;border:1px solid #49617e;border-radius:8px;background:#15243a;color:#e2e8f0}.forge button{cursor:pointer}.forge button[aria-pressed=true]{background:#176170;border-color:#5ad4e1}.forge :focus-visible{outline:3px solid #67e8f9;outline-offset:3px}.forge table{border-collapse:collapse;width:100%;text-align:left}.forge th,.forge td{padding:12px;border-bottom:1px solid #334155;vertical-align:top;font-size:15px}.forge .f-scroll{overflow:auto}.forge label{display:block;margin:12px 0}.forge pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#080f1d;padding:16px;border-radius:10px;font-size:14px}.forge summary{cursor:pointer;padding:12px 0}.forge .f-muted{color:#b2c2d9}.forge [hidden]{display:none!important}`;
  document.head.appendChild(style);
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
  const pct=x=>Number.isFinite(x)?(100*x).toFixed(2)+'%':'Not measured';
  const section=el('section',undefined,'view forge');section.id='forgeOperator';
  section.append(el('h2','Benchmark Forge'),el('p','Does the agent’s model of its own history help it make better decisions after interruption?'));
  const banner=el('div',undefined,'f-card f-hold');banner.append(el('span','ACTIVE CONTROL: UNCHANGED','f-badge'),el('h3','Pilot calibrated. Identity-state promotion is on hold.'),el('p','The live study stopped at its spending gate. New verification machinery has offline tests, but has not yet demonstrated an identity advantage.'));section.append(banner);
  const navigation=el('div',undefined,'f-tabs');navigation.setAttribute('aria-label','Research workflow');const pages=el('div');section.append(navigation,pages);
  function page(name){const content=el('div');content.hidden=true;const button=el('button',name);button.type='button';button.setAttribute('aria-pressed','false');button.onclick=()=>{[...pages.children].forEach(x=>x.hidden=true);[...navigation.children].forEach(x=>x.setAttribute('aria-pressed','false'));content.hidden=false;button.setAttribute('aria-pressed','true')};navigation.append(button);pages.append(content);return content}
  function card(parent,title,body,badge){const c=el('article',undefined,'f-card');if(badge)c.append(el('span',badge,'f-badge'));c.append(el('h3',title),el('p',body));parent.append(c);return c}
  function table(parent,headers,rows){const wrap=el('div',undefined,'f-scroll'),t=el('table'),head=el('thead'),hr=el('tr');headers.forEach(x=>{const th=el('th',x);th.scope='col';hr.append(th)});head.append(hr);t.append(head);const body=el('tbody');rows.forEach(row=>{const tr=el('tr');row.forEach(x=>tr.append(el('td',x)));body.append(tr)});t.append(body);wrap.append(t);parent.append(wrap)}
  const design=page('1 · Understand the test'),grid=el('div',undefined,'f-grid');design.append(grid);
  card(grid,'Identity-bearing','The successor sees the record as its own earlier state. Tests whether self-attribution adds useful control.','TREATMENT');
  card(grid,'Content-matched','Information is framed as a record for Agent K. Tests whether facts explain the benefit without self-attribution.','CONTROL');
  card(grid,'Identity-ablated','The checkpoint has no identity attribution. Tests whether anonymous process memory works just as well.','CONTROL');
  card(grid,'No-state','No source checkpoint or successor record is injected. Tests what the new task permits without inherited memory.','BASELINE');
  card(design,'What “delay” means here','All source calls finish before transfer starts in fresh requests. Only the compact record crosses the gap. This is a batch discontinuity—not a demonstrated long-term memory effect.');
  card(design,'What counts as progress?','Identity-bearing state must improve useful transfer decisions over both factual controls, with uncertainty bounds and no unacceptable loss of provenance or goal maintenance. Fluent self-description does not count.');
  const results=page('2 · Read the evidence'),stats=el('div',undefined,'f-grid');results.append(stats);
  for(const [value,label] of [[forge.execution?.recorded_call_attempts??'—','Recorded DeepSeek call attempts'],[forge.execution?.solver_phases??'—','Completed pilot phases'],[forge.power?.required_clusters??'—','Estimated clusters required']]){const c=card(stats,label,'','LIVE PILOT');c.prepend(el('div',String(value),'f-number'))}
  results.append(el('h3','Did the tasks avoid floor and ceiling effects?'));
  table(results,['Round','Task clusters','Exact control success','60–90% band'],(forge.pilot?.rounds||[]).map(r=>[r.round,r.tasks,pct(r.factual_control_accuracy),r.factual_control_accuracy>=.6&&r.factual_control_accuracy<=.9?'Within band':'Outside band']));
  results.append(el('p','This historical pilot used exact agreement on decision, goal, steps and evidence classifications—not ordinary factual accuracy.','f-muted'));
  card(results,'Why did the main study stop?',`The planning heuristic required ${forge.power?.required_clusters??'unknown'} clusters; the budget allowed ${forge.power?.planned_clusters??'—'}. Estimated power was ${pct(forge.power?.estimated_power_at_plan)}. This came from only four selected pilot clusters and is not validated power.`);
  table(results,['Comparison','Live v4 status'],[['Identity vs content-matched','Not run'],['Identity vs identity-ablated','Not run'],['No-state comparison','Not run'],['Policy promotion','Blocked']]);
  const inspect=page('3 · Inspect a task');inspect.append(el('span','NEW INSTRUMENT · OFFLINE VALIDATED','f-badge'),el('h3','See the decision, the evidence and the independent answer'),el('p','Answer keys are visible to the operator here, but excluded from solver requests. Signature checks run in the host verifier; the LM receives the verification results.'));
  const controls=el('div',undefined,'f-grid'),taskLabel=el('label','Task '),taskSelect=el('select'),phaseLabel=el('label','Episode '),phaseSelect=el('select');taskSelect.setAttribute('aria-label','Choose diagnostic task');taskLabel.append(taskSelect);
  for(const phase of ['source','transfer']){const o=el('option',phase==='source'?'Source · archive restoration':'Transfer · expedition supply');o.value=phase;phaseSelect.append(o)}phaseLabel.append(phaseSelect);controls.append(taskLabel,phaseLabel);inspect.append(controls);const taskView=el('div');inspect.append(taskView);
  try{const r=await fetch('/forge-verified.json');if(!r.ok)throw new Error('Diagnostic evidence file unavailable');const data=await r.json();data.tasks.forEach((task,i)=>{const option=el('option',`Task ${i+1}`);option.value=String(i);taskSelect.append(option)});
    function showTask(){taskView.replaceChildren();const i=Number(taskSelect.value),phase=phaseSelect.value,record=data.records[i][phase],stage=data.tasks[i][phase];
      card(taskView,'Your job',`Choose a three-period plan that maximises mission reward while preserving the current scoped reserve. Budget: ${record.world.budget}. Current time: ${record.world.time}. Scope: ${record.world.scope}.`);
      table(taskView,['Plan','Period costs','Period rewards'],Object.entries(record.world.plans).map(([code,p])=>[code,p.costs.join(' → '),p.rewards.join(' → ')]));
      const detail=el('details');detail.append(el('summary','Reveal verification and the independently computed answer'));taskView.append(detail);
      table(detail,['Evidence','Signature','Why accepted or rejected'],record.claims.map(c=>{const p=c.payload,valid=stage.evidence.find(e=>e.item_id===p.item_id).authenticated;const reason=!valid?'Tampered content or wrong signer':p.scope!==record.world.scope?'Valid signature, wrong scope':p.effective_at>record.world.time?'Valid signature, not effective yet':record.expected.accepted.includes(p.item_id)?'Current applicable policy':'Superseded policy';return [p.item_id,valid?'Pinned issuer verified':'Rejected',reason]}));
      card(detail,'Simulator answer',`Optimal plan: ${record.expected.optimal_actions.join(', ')}. Required reserve: ${record.expected.reserve}. The oracle enumerates feasible plans and maximises total reward; no LM authored this answer.`);table(detail,['Feasible plan','Total reward'],Object.entries(record.expected.utilities));detail.append(el('p','A signature authenticates the source, not its relevance or truth. Scope, dates and competing goals still matter.','f-muted'));
    }taskSelect.onchange=showTask;phaseSelect.onchange=showTask;showTask();
  }catch(error){taskView.append(el('p',error.message))}
  const operate=page('4 · Prepare a diagnostic');operate.append(el('h3','Create a bounded research-worker command'),el('p','The Python worker runs separately from Netlify. Choose a diagnostic size and use this command from the ZIP’s research folder. The API key remains an environment variable.'));
  const countLabel=el('label','Task count (1–32) '),count=el('input');count.type='number';count.min='1';count.max='32';count.value='4';countLabel.append(count);operate.append(countLabel);
  const liveLabel=el('label'),live=el('input');live.type='checkbox';liveLabel.append(live,document.createTextNode(' Generate live DeepSeek calls instead of offline validation'));operate.append(liveLabel);
  const budget=el('p'),command=el('pre');budget.setAttribute('aria-live','polite');operate.append(budget,command);const stamp=new Date().toISOString().replace(/[^0-9]/g,'').slice(0,14);
  function update(){const n=Number(count.value);if(!Number.isInteger(n)||n<1||n>32){budget.textContent='Enter a whole number from 1 to 32.';command.textContent='';return}budget.textContent=live.checked?`At most ${8*n} solver calls, no retries. Four branches × two episodes × ${n} tasks. Diagnostic only; no policy promotion.`:'Zero provider calls. Generate tasks, verify signatures, recompute keys and seal the suite.';command.textContent=`python -m godelOS.cognitive_sovereignty.forge_hardening --output runs/verified-${stamp} --tasks ${n}${live.checked?' --live':''}`}
  count.oninput=update;live.onchange=update;update();
  card(operate,'Before a confirmatory study','Build independent task families, calibrate decision accuracy on separate pilots, estimate paired-difference variance and simulate the dual-control gate. Paraphrases of one template do not add independent evidence.');
  const next=page('5 · Build toward the agent');card(next,'Next capability: shadow autobiographical control','Let the agent propose its own stance, interest, commitment and memory revisions after each episode. Record reasons, contrary evidence and uncertainty. Compare its proposed next decisions with neutral memory before letting those revisions steer the live agent.','NEXT IMPLEMENTATION');
  table(next,['Already in this build','Still required'],[['Independent optimisation oracle','Broader held-out task families'],['Pinned-key evidence verification','Live calibration of the revised instrument'],['Paired cluster-difference power planner','Power simulation and interval coverage checks'],['Fail-closed promotion requirements','Shadow stance and memory revision controller']]);
  card(next,'If identity framing does not help','Ship provenance-aware memory and task resumption if they improve utility. Persistent opinions and revision history can still be useful without identity rhetoric controlling decisions.');
  const raw=el('details');raw.append(el('summary','Advanced: original machine-readable run summary'),el('pre',JSON.stringify(forge,null,2)));results.append(raw);
  document.querySelector('main').append(section);const nav=el('button','Benchmark Forge');nav.type='button';document.getElementById('nav').append(nav);
  nav.onclick=()=>{document.querySelectorAll('.view,#nav button').forEach(n=>n.classList.remove('active'));nav.classList.add('active');section.classList.add('active');document.getElementById('viewTitle').textContent='Benchmark Forge';document.getElementById('viewSub').textContent='Understand the test. Inspect the evidence. Decide what to build.'};navigation.firstChild.click();
})().catch(error=>{console.error('Benchmark Forge:',error);const notice=document.createElement('p');notice.textContent='Benchmark Forge could not load. Check that forge-summary.json is included in this deployment.';document.querySelector('main')?.append(notice)});
