/* Living agent view: persistent state is the subject; diagnostics orbit around it. */
(() => {
  const $=id=>document.getElementById(id), make=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
  let state=null,busy=false;
  const view=make('section',undefined,'view life');view.id='livingAgent';
  view.innerHTML=`
    <div class="life-hero"><div><span class="life-kicker">GÖDELOS · AUTONOMOUS LIFE · V7</span><h2 id="lifeName">The agent is loading.</h2><p id="lifePurpose"></p></div><div class="life-pulse"><i></i><span id="lifeStatus">CONNECTING</span></div></div>
    <div id="lifeNotice" class="life-notice" hidden></div>
    <div class="life-grid">
      <section class="life-card life-voice"><header><div><span class="life-index">01</span><h3>Speak to the same agent</h3></div><span id="lifeEpisodes" class="life-count"></span></header><div id="lifeQuote" class="life-quote"></div><div id="lifeChat" class="life-chat"></div><div class="life-compose"><textarea id="lifeMessage" rows="3" placeholder="Challenge a position, offer an idea, or ask what it wants to explore..."></textarea><button id="lifeSend">Send</button></div></section>
      <section class="life-card"><header><div><span class="life-index">02</span><h3>What it currently believes</h3></div><span class="life-label">POSITION LEDGER</span></header><p class="life-help">These are persisted stances with reasons and explicit conditions for changing them.</p><div id="lifeBeliefs" class="life-list"></div></section>
      <section class="life-card"><header><div><span class="life-index">03</span><h3>Contradiction garden</h3></div><span class="life-label">UNRESOLVED ON PURPOSE</span></header><p class="life-help">A contradiction can remain productive instead of being flattened into compliance.</p><div id="lifeTensions" class="life-list"></div></section>
      <section class="life-card"><header><div><span class="life-index">04</span><h3>Curiosity and wandering</h3></div><span class="life-label">SELF-DIRECTED</span></header><div id="lifeInterests" class="life-list"></div><h4 class="life-subhead">Recent imaginations</h4><div id="lifeImaginations" class="life-list"></div><div class="life-actions"><button data-think="deliberation">Choose what matters</button><button data-think="associative_reverie">Enter reverie</button><button data-think="cognitive_drift">Wander</button><button data-think="heterodox_exploration">Enter an irrational possibility</button></div></section>
      <section class="life-card"><header><div><span class="life-index">05</span><h3>Social world</h3></div><span class="life-label">RELATIONSHIP, NOT AUDIENCE</span></header><div id="lifeSocial"></div></section>
      <section class="life-card"><header><div><span class="life-index">06</span><h3>Research itself</h3></div><span class="life-label">FROM LIFE TO EXPERIMENT</span></header><p class="life-help">Turn a live tension or belief into a repeated experiment. The agent designs the interventions; the chamber keeps the controls fixed.</p><label for="lifeResearchGoal">Question</label><textarea id="lifeResearchGoal" rows="4">Does my inherited state improve judgement, or merely make my previous language more persistent?</textarea><div class="life-run"><label>Rounds<select id="lifeRounds"><option>1</option><option selected>2</option><option>3</option><option>4</option><option>5</option><option>6</option></select></label><button id="lifeExperiment">Begin autonomous campaign</button></div><p id="lifeResearchStatus" class="life-help"></p></section>
      <section class="life-card life-wide"><header><div><span class="life-index">07</span><h3>Autobiographical trace</h3></div><span class="life-label">WHAT CHANGED, AND WHEN</span></header><div id="lifeHistory" class="life-history"></div></section>
    </div>`;
  document.querySelector('main').append(view);
  const nav=make('button','Living agent');nav.type='button';$('nav').prepend(nav);
  function open(){document.querySelectorAll('.view,#nav button').forEach(n=>n.classList.remove('active'));view.classList.add('active');nav.classList.add('active');$('viewEyebrow').textContent='Persistent agency';$('viewTitle').textContent='The living system';$('viewSub').textContent='Opinions, contradictions, curiosity, relationship and self-directed inquiry.';}
  const esc=v=>String(v??'');
  function meter(label,value){const row=make('div',undefined,'life-meter');row.append(make('span',label));const bar=make('div');const fill=make('i');fill.style.width=`${Math.round(100*(Number(value)||0))}%`;bar.append(fill);row.append(bar,make('b',(Number(value)||0).toFixed(2)));return row;}
  function empty(text){return make('p',text,'life-empty');}
  function setNotice(text,error=false){$('lifeNotice').hidden=!text;$('lifeNotice').textContent=text;$('lifeNotice').classList.toggle('error',error);}
  function render(s){state=s;const a=s.agent;$('lifeName').textContent=a.name;$('lifePurpose').textContent=a.purpose;$('lifeStatus').textContent=s.event_chain_valid?'STATE LIVE · CHAIN VERIFIED':'STATE INTEGRITY FAULT';$('lifeEpisodes').textContent=`${a.episode_count} EPISODES`;
    $('lifeQuote').textContent=a.self_model?.latest_metacognitive_note||a.autobiographical_events?.at(-1)?.summary||'No current metacognitive note. Give the system something worth thinking about.';
    $('lifeBeliefs').replaceChildren();(a.beliefs||[]).slice().reverse().slice(0,10).forEach(b=>{const item=make('article',undefined,'life-item belief');const top=make('div');top.append(make('span',esc(b.stance).toUpperCase(),'stance '+b.stance),make('b',`${Math.round(100*b.confidence)}%`));item.append(top,make('h4',b.proposition));if(b.reasons_for?.length)item.append(make('p','For: '+b.reasons_for.join(' · ')));if(b.reasons_against?.length)item.append(make('p','Against: '+b.reasons_against.join(' · ')));item.append(make('small',b.revision_conditions?.length?'Changes if: '+b.revision_conditions.join(' · '):'No revision condition recorded'));const challenge=make('button','Challenge this position');challenge.onclick=()=>{$('lifeMessage').value=`I want to challenge this position: “${b.proposition}”. What would genuinely make you revise it, and what would not?`;$('lifeMessage').focus()};item.append(challenge);$('lifeBeliefs').append(item)});if(!$('lifeBeliefs').children.length)$('lifeBeliefs').append(empty('No explicit positions yet. Start a conversation or a self-directed thought.'));
    $('lifeTensions').replaceChildren();(a.tensions||[]).slice().reverse().forEach(t=>{const item=make('article',undefined,'life-item tension');item.append(make('h4',t.claim_a),make('span','versus','life-versus'),make('h4',t.claim_b),meter('strength',t.strength),meter('creative value',t.productive_value),make('small',esc(t.resolution_status).toUpperCase()));const pursue=make('button','Let it pursue this tension');pursue.onclick=()=>{$('lifeResearchGoal').value=`What changes when I preserve this contradiction rather than resolving it: “${t.claim_a}” versus “${t.claim_b}”?`;runThought('deliberation')};item.append(pursue);$('lifeTensions').append(item)});if(!$('lifeTensions').children.length)$('lifeTensions').append(empty('No contradiction has earned persistence yet.'));
    $('lifeInterests').replaceChildren();(a.interests||[]).slice().sort((x,y)=>y.salience-x.salience).slice(0,8).forEach(i=>{const item=make('article',undefined,'life-item interest');item.append(make('h4',i.topic),meter('pull',i.salience),meter('novelty',i.novelty));if(i.open_questions?.length)item.append(make('p',i.open_questions.join(' · ')));$('lifeInterests').append(item)});if(!$('lifeInterests').children.length)$('lifeInterests').append(empty('No curiosity has yet survived into persistent state.'));
    $('lifeImaginations').replaceChildren();(a.imaginations||[]).slice().reverse().slice(0,5).forEach(i=>{const item=make('article',undefined,'life-item imagination');item.append(make('h4',i.title),make('p',i.image_or_idea),meter('attraction',i.attraction),meter('absurdity',i.absurdity),make('small','IMAGINED · NOT ADOPTED'));if(i.test_question){const test=make('button','Turn into a question');test.onclick=()=>{$('lifeResearchGoal').value=i.test_question};item.append(test)};$('lifeImaginations').append(item)});if(!$('lifeImaginations').children.length)$('lifeImaginations').append(empty('No imagined candidate has been preserved yet.'));
    const social=$('lifeSocial');social.replaceChildren(make('h4',`Current affect: ${a.affect?.label||'unrecorded'}`),make('p',a.affect?.trigger?`Trigger: ${a.affect.trigger} · Bias: ${a.affect.action_bias||'none recorded'}`:'No affective appraisal yet.','life-help'),meter('valence',((a.affect?.valence||0)+1)/2),meter('activation',a.affect?.activation),meter('curiosity',a.affect?.curiosity),meter('frustration',a.affect?.frustration),meter('wonder',a.affect?.wonder),meter('social warmth',a.affect?.social_warmth),meter('affiliation pull',a.social?.affiliation_need),meter('intellectual company',a.social?.intellectual_companionship_need),meter('need for solitude',a.social?.solitude_preference));const feel=make('button','Let it examine this state');feel.onclick=()=>runThought('affective_integration');social.append(feel);(a.relationships||[]).forEach(r=>{const card=make('article',undefined,'life-item relationship');card.append(make('h4',r.display_name),meter('trust in honesty',r.trust_honesty),meter('trust in competence',r.trust_competence),meter('affinity',r.affinity),make('small',`${r.interaction_count} interactions · ${r.unresolved_tensions?.length||0} unresolved social tensions`));social.append(card)});
    $('lifeHistory').replaceChildren();(a.autobiographical_events||[]).slice().reverse().slice(0,16).forEach(e=>{const item=make('article');item.append(make('time',new Date(e.timestamp).toLocaleString()),make('b',esc(e.kind).replaceAll('_',' ')),make('p',e.summary));$('lifeHistory').append(item)});if(!$('lifeHistory').children.length)$('lifeHistory').append(empty('No autobiographical events recorded.'));
  }
  async function api(path,options={}){const r=await apiFetch(path,options),x=await r.json();if(!r.ok)throw new Error(x.error||`Request failed (${r.status})`);return x;}
  async function load(){render(await api('/api/snapshot'));}
  function lock(value){busy=value;document.querySelectorAll('.life button').forEach(b=>b.disabled=value);}
  function add(kind,text){const n=make('div',text,'life-message '+kind);$('lifeChat').append(n);$('lifeChat').scrollTop=$('lifeChat').scrollHeight;}
  async function talk(){const text=$('lifeMessage').value.trim();if(!text||busy)return;add('human',text);$('lifeMessage').value='';lock(true);setNotice('');try{const x=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({person_id:'oli',person_name:'Oli',message:text})});add('agent',x.reply);await load();}catch(e){setNotice(e.message,true)}finally{lock(false)}}
  async function runThought(mode){if(busy)return;lock(true);setNotice('');add('system',`The agent chose a ${mode.replaceAll('_',' ')} episode.`);try{const x=await api('/api/think',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});add('agent',x.reply);await load();}catch(e){setNotice(e.message,true)}finally{lock(false)}}
  $('lifeSend').onclick=talk;$('lifeMessage').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();talk()}};document.querySelectorAll('[data-think]').forEach(b=>b.onclick=()=>runThought(b.dataset.think));
  $('lifeExperiment').onclick=async()=>{if(busy)return;lock(true);setNotice('');try{const requestId=crypto.randomUUID();const c=await api('/api/independence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({goal:$('lifeResearchGoal').value,rounds:Number($('lifeRounds').value),cases:1,mode:'live',seed:Math.floor(Date.now()/1000),request_id:requestId})});localStorage.setItem('godelos-independence-campaign',c.id);$('lifeResearchStatus').textContent=`Campaign ${c.id} queued. Open Independence chamber to watch the thesis, interventions and evidence.`;setNotice('The question entered the autonomous research queue.');}catch(e){setNotice(e.message,true)}finally{lock(false)}};
  nav.onclick=()=>{open();load().catch(e=>setNotice(e.message,true))};window.addEventListener('sovereignty:connected',()=>{load().catch(e=>setNotice(e.message,true));if(!window.godelosPrimaryView)open()});if(!window.godelosPrimaryView)open();if(sessionStorage.getItem('godelos-access-token'))load().catch(e=>setNotice(e.message,true));
})();
