const $=id=>document.getElementById(id),node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const theme=localStorage.getItem('godelos-theme')||(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light');
function setTheme(t){document.body.dataset.theme=t;$('theme').textContent=t==='dark'?'Light mode':'Dark mode';$('theme').setAttribute('aria-pressed',String(t==='dark'));localStorage.setItem('godelos-theme',t);}setTheme(theme);$('theme').onclick=()=>setTheme(document.body.dataset.theme==='dark'?'light':'dark');
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!==b.dataset.panel);});
async function api(path,body){const token=sessionStorage.getItem('godelos-access-token');if(!token)throw Error('Open the agent and enter your access token, then return here.');const r=await fetch('/api/'+path,{headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body===undefined?{}:{method:'POST',body:JSON.stringify(body)})});const x=await r.json();if(!r.ok)throw Error(x.error||'Request failed');return x;}
async function busy(button,status,work){button.disabled=true;status.textContent='Working…';const began=Date.now(),timer=setInterval(()=>status.textContent=`Working · ${Math.floor((Date.now()-began)/1000)}s`,1000);try{const message=await work();status.textContent=message;}catch(e){status.textContent=e.message;}finally{clearInterval(timer);button.disabled=false;}}
const labels={identity:'Identity-bearing',content_matched:'Content-matched',ablated:'Ablated',no_state:'No state'};
fetch('/release-evidence.json').then(r=>{if(!r.ok)throw Error('Recorded evidence is unavailable in this build');return r.json();}).then(data=>{const a=data.primary;for(const [value,label] of [[a.execution.calls,'real provider calls'],[a.arms.identity.n*4,'transfer decisions'],[a.power.clusters,'paired scenario clusters'],[a.execution.errors.length,'provider errors']]){const box=node('div',undefined,'metric');box.append(node('b',String(value)),node('span',label));$('metrics').append(box);}for(const [arm,result] of Object.entries(a.arms)){const row=node('div',undefined,'bar-row'),track=node('div',undefined,'bar-track'),fill=node('div',undefined,'bar-fill');fill.style.width=(result.accuracy*100)+'%';track.append(fill);row.append(node('span',labels[arm]),track,node('b',(100*result.accuracy).toFixed(1)+'%'));$('armChart').append(row);}$('verdict').textContent='Identity adoption held · '+a.execution.model_names.join(', ')+' · recorded campaign';const c=a.contrasts[0];$('uncertainty').textContent=`Identity minus content-matched: ${(100*c.gain).toFixed(1)} percentage points; paired scenario interval ${(100*c.interval[0]).toFixed(1)} to ${(100*c.interval[1]).toFixed(1)}. ${a.power.clusters} clusters were run; planning assumptions call for ${a.power.required_clusters}. These are exploratory results.`;}).catch(e=>$('verdict').textContent=e.message);
let goals=[];
async function loadGoals(){const s=await api('snapshot');goals=(s.agent?.mind?.intentions||[]).filter(g=>['active','blocked'].includes(g.status));$('goalList').replaceChildren();$('goalSelect').replaceChildren(node('option','Choose an active goal'));$('goalSelect').firstChild.value='';for(const g of goals){const card=node('div',undefined,'goal-card');card.append(node('b',g.goal),node('p',`Recorded step ${g.step} / ${g.steps.length} · Verified advances ${g.verified_revision||0} · ${g.status}`));if(g.progress_claim)card.append(node('p','Unverified claim: '+g.progress_claim.reason));if(g.verification_contract)card.append(node('p','Acceptance test registered: '+g.verification_contract.kind));$('goalList').append(card);const option=node('option',g.goal);option.value=g.id;$('goalSelect').append(option);}return goals.length?`${goals.length} unresolved goals loaded.`:'No unresolved goals. Talk with the agent to form an intention.';}
$('refreshGoals').onclick=()=>busy($('refreshGoals'),$('goalStatus'),loadGoals);
$('contract').value=JSON.stringify({kind:'budget_plan',cases:[{budget:3,options:[{id:'a',cost:4,utility:10},{id:'b',cost:2,utility:5}]},{budget:5,options:[{id:'a',cost:4,utility:10},{id:'b',cost:2,utility:5}]}]},null,2);
for(const [id,action] of [['bindGoal','bind'],['verifyGoal','submit']])$(id).onclick=()=>busy($(id),$('verificationResult'),async()=>{const g=goals.find(g=>g.id===$('goalSelect').value);if(!g)throw Error('Choose an active goal first.');const result=await api('mind/intention/verify',{intention_id:g.id,expected_step:g.step,action,...(action==='bind'?{contract:JSON.parse($('contract').value)}:{artifact:JSON.parse($('artifact').value)})});await loadGoals();return JSON.stringify(result,null,2);});
function showReview(r){$('promotionReasons').replaceChildren();for(const text of r?.judgment?.reasons||[])$('promotionReasons').append(node('p',text));}
$('promotionRefresh').onclick=()=>busy($('promotionRefresh'),$('promotionStatus'),async()=>{const s=await api('promotion/status');showReview(s.latest_review);return s.adapter_installed?'Task verifier installed; inspect the current review.':'Adoption held. The production long-horizon task-verifier adapter is not yet installed.';});
$('reviewCandidate').onclick=()=>busy($('reviewCandidate'),$('promotionStatus'),async()=>{const pkg=await api('evolution/latest');if(!pkg)throw Error('No candidate yet. Start a development round in the agent’s Research view.');const r=await api('promotion/review',{id:pkg.content.id});showReview(r);return r.phase==='held'?'Candidate reviewed: adoption held. Read the reasons below.':r.phase;});
