/* Inspectable inputs and outputs. No hidden model state is inferred here. */
window.addEventListener('DOMContentLoaded',()=>{
 const $=id=>document.getElementById(id),el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;},human=s=>String(s||'').replaceAll('_',' ');
 document.querySelector('.md-build').textContent='V13 · Living Mind alpha';
 const controllerTitle=document.querySelector('.md-evolution summary');if(controllerTitle)controllerTitle.textContent='Controller experiments · candidate policies';
 const activity=document.querySelector('.md-activity'),intro=document.querySelector('.md-chat-intro');
 intro.querySelector('.md-overline').textContent='GÖDELOS / A CONTINUING MIND';intro.querySelector('h2').textContent='A thought can become a thread.';intro.querySelector('p').textContent='Bring an idea. Follow a curiosity. See what changes its mind.';
 const compass=el('button','studio-compass');compass.type='button';compass.setAttribute('aria-label','Inspect the inputs shaping the current thought');
 compass.innerHTML='<svg viewBox="0 0 100 70" aria-hidden="true"><path d="M8 16C35 16 29 35 50 35S67 12 91 12M8 54C32 54 30 35 50 35S70 58 91 58M8 35H91"/><circle cx="8" cy="16" r="4"/><circle cx="8" cy="35" r="4"/><circle cx="8" cy="54" r="4"/><circle class="studio-compass-core" cx="50" cy="35" r="10"/><circle cx="91" cy="12" r="4"/><circle cx="91" cy="35" r="4"/><circle cx="91" cy="58" r="4"/></svg><span><b id="studioFocusMini">Room for a first thought</b><small id="studioFlowMini">Input → attention → memory · inspect the loop</small></span><span aria-hidden="true">↗</span>';
 intro.after(compass);compass.onclick=()=>document.querySelector('button[aria-label="Activity"]').click();
 const heading=activity.querySelector('.md-section-heading');heading.querySelector('h2').textContent='What shapes the next thought?';heading.querySelector('p').textContent='Follow attention, inspect a change of mind, or let the agent explore between conversations.';
 const status=el('section','studio-autonomy');status.setAttribute('aria-label','Background thinking');status.innerHTML='<div><span class="studio-eyebrow">BACKGROUND THINKING</span><h3 id="studioRunState">Connecting…</h3><p id="studioRunDetail"></p></div><div class="studio-budget"><b id="studioBudget">—</b><span>background calls today</span><meter id="studioBudgetMeter" min="0" max="24" value="0" aria-label="Background daily call usage"></meter></div><button id="studioRecoverWorker" type="button" hidden>Recover background worker</button><p id="studioRecoveryNote" role="status" hidden></p>';heading.after(status);
 const graphic=el('section','studio-flow');graphic.setAttribute('aria-label','Recorded workspace inputs and outputs');graphic.innerHTML='<div class="studio-flow-head"><span class="studio-eyebrow">THE LAST RECORDED CYCLE</span><span id="studioSelection" class="studio-pill">No selection yet</span></div><div class="studio-flow-grid"><div><h4>Inputs compete</h4><p>Score contributions from the attention controller.</p><div id="studioBids"></div></div><div class="studio-broadcast"><span class="studio-broadcast-symbol" aria-hidden="true">✳</span><h4>One shared focus</h4><p id="studioBroadcastFocus">Run a thought cycle to populate the trace.</p><span>Available to the model, memory and the next selection</span></div><div class="studio-carry"><h4>Carried forward</h4><dl><div><dt>Retrieved memories</dt><dd id="studioRetrieved">0</dd></div><div><dt>Cited by the response</dt><dd id="studioCited">0</dd></div><div><dt>Stance revisions</dt><dd id="studioStanceCount">0</dd></div><div><dt>Intention updates</dt><dd id="studioIntentionCount">0</dd></div></dl><p id="studioTraceNote">A saved trace appears after a completed cycle.</p></div></div><p class="studio-caption">These are the application’s explicit control paths. Scores are attention bids, not confidence or a measure of felt experience.</p>';document.querySelector('.mind-focus').after(graphic);
 const ledger=el('details','mind-card mind-detail studio-ledger');ledger.innerHTML='<summary>Positions & changes of mind <span id="studioPositionTotal"></span></summary><p class="mind-muted">A position can stay firm, become conflicted or change. New revisions preserve the previous stance and its stated reasons.</p><div id="studioStances"></div>';document.querySelector('.md-state-grid').append(ledger);
 const tile=el('div','md-tool'),report=el('a','studio-report','V10 build & evaluation report ↗');report.href='/godelos-workspace-v10-report.pdf';report.target='_blank';report.rel='noopener';tile.append(report,el('p',null,'Architecture, real diagnostic results, limitations and the next engineering decision.'));document.querySelector('#operatorArchive .md-archive-grid').prepend(tile);
 const dock=el('aside','studio-live');dock.id='studioLive';dock.hidden=true;dock.setAttribute('aria-live','polite');dock.innerHTML='<header><div><span class="studio-eyebrow">LIVE OPERATION</span><h3 id="studioLiveTitle">Working</h3></div><span id="studioLiveClock">0.0s</span><button id="studioLiveClose" type="button" aria-label="Dismiss operation status">×</button></header><ol id="studioLivePhases"><li>Input secured</li><li>Context assembled</li><li>Model responding</li><li>Output validated</li><li>State committed</li></ol><div class="studio-live-track"><i id="studioLiveTrack"></i></div><p id="studioLiveDetail">Preparing the request.</p><blockquote id="studioLiveReply" hidden></blockquote><footer><span id="studioLiveModel">Model pending</span><span id="studioLiveState">State unchanged</span></footer>';document.body.append(dock);
 const phaseOrder=['reserved','context','first_token','state_ready','committed'];let liveActive=false,startedAt=0,timer=null,hideTimer=null,genericOperation=null,suppressGenericUntil=0;
 const setClock=()=>{$('studioLiveClock').textContent=((Date.now()-startedAt)/1000).toFixed(1)+'s';};
 const showLive=(title,detail)=>{clearTimeout(hideTimer);dock.hidden=false;dock.classList.remove('is-complete','is-failed');$('studioLiveTitle').textContent=title;$('studioLiveDetail').textContent=detail;startedAt=Date.now();clearInterval(timer);timer=setInterval(setClock,100);setClock();};
 const setPhase=(index,detail)=>{const steps=[...$('studioLivePhases').children];steps.forEach((step,n)=>{step.dataset.state=n<index?'done':n===index?'active':'waiting';});$('studioLiveTrack').style.width=Math.max(4,Math.min(100,5+index*23.75))+'%';if(detail)$('studioLiveDetail').textContent=detail;};
 const finishLive=(failed=false,completePhases=true)=>{clearInterval(timer);setClock();dock.classList.add(failed?'is-failed':'is-complete');if(!failed&&completePhases){[...$('studioLivePhases').children].forEach(x=>x.dataset.state='done');$('studioLiveTrack').style.width='100%';}hideTimer=setTimeout(()=>{if(!liveActive)dock.hidden=true;},7000);};
 $('studioLiveClose').onclick=()=>{dock.hidden=true;clearTimeout(hideTimer);};
 window.godelosLiveOperation={
  begin(meta){liveActive=true;genericOperation=null;$('studioLivePhases').hidden=false;$('studioLiveReply').hidden=true;$('studioLiveReply').textContent='';$('studioLiveModel').textContent='Model pending';$('studioLiveState').textContent='State unchanged';showLive(meta.kind==='conversation'?'Responding to you':'Running a thought cycle','Reserving one immutable attempt.');setPhase(0);},
  phase(event){const p=event.phase;let index=phaseOrder.indexOf(p);if(p==='provider')index=2;if(p==='validating')index=3;if(p==='committing')index=4;if(index<0)index=0;const details={queued:'Your message entered the priority queue.',reserved:'Input recorded. No second provider call can reuse this request.',context:event.focus?`${human(event.focus.kind)} selected · ${event.retrieved_memories} memories retrieved · ${event.competitors} alternatives scored.`:'The next focus and relevant memories are assembled.',provider:event.status==='connected'?`Connected to ${event.requested_model||'the configured model'}. Waiting for the first token.`:'Opening the model stream.',first_token:'The reply is arriving now. Persistent state is still unchanged.',validating:`Complete response received in ${((event.latency_ms||0)/1000).toFixed(1)}s. Checking schema, provenance and references.`,state_ready:event.state_updates_applied?'Output passed validation. Preparing an atomic state write.':'Reply recovered. Proposed state changes were quarantined.',committing:`Writing state version ${event.target_state_version}.`,committed:`Cycle ${event.mind_tick} committed as state version ${event.state_version}.`};setPhase(index,details[p]);if(event.model)$('studioLiveModel').textContent='Actual model · '+event.model;if(event.state_version)$('studioLiveState').textContent='State v'+event.state_version;},
  reply(text){$('studioLiveReply').hidden=false;$('studioLiveReply').textContent=text;},
  finish(result){liveActive=false;suppressGenericUntil=Date.now()+1800;if(result?.model)$('studioLiveModel').textContent='Actual model · '+result.model;if(result?.state_version)$('studioLiveState').textContent='State v'+result.state_version;$('studioLiveTitle').textContent=result?.queued?'Queued for the next opening':'Cycle complete';$('studioLiveDetail').textContent=result?.queued?'Another cycle owns the current lease. This message remains visible in the queue.':result?.warnings?.length?'Reply delivered. Invalid state updates were quarantined and recorded.':'Reply delivered and the validated state transition is durable.';finishLive(false,!result?.queued);},
  fail(error){liveActive=false;suppressGenericUntil=Date.now()+1800;$('studioLiveTitle').textContent='Attempt stopped';$('studioLiveDetail').textContent=error.message||'The operation failed.';$('studioLiveState').textContent='No state commit';finishLive(true);},
 };
 const operationName=url=>url.includes('/evolution/')?'Testing a controller candidate':url.includes('/forge/')?'Advancing an experiment':url.includes('/independence')?'Advancing self-directed research':url.includes('/value-profile')?'Saving a value candidate':url.includes('/snapshot')?'Refreshing recorded state':'Contacting the runtime';
 document.addEventListener('godelos:network',event=>{const d=event.detail;if(liveActive||(d.stage==='begin'&&(d.method==='GET'||Date.now()<suppressGenericUntil)))return;if(d.stage==='begin'){genericOperation=d.operation_id;showLive(operationName(d.url),'Request sent. Waiting for the runtime.');$('studioLivePhases').hidden=true;$('studioLiveReply').hidden=true;$('studioLiveTrack').style.width='18%';}else if(d.operation_id===genericOperation){if(d.stage==='response'){$('studioLiveTitle').textContent=d.ok?'Operation complete':'Request refused';$('studioLiveDetail').textContent=d.ok?'The runtime returned a result. The active view is updating.':`The runtime returned HTTP ${d.status}.`;genericOperation=null;finishLive(!d.ok,false);}else if(d.stage==='error'){$('studioLiveTitle').textContent='Connection failed';$('studioLiveDetail').textContent=d.message;genericOperation=null;finishLive(true);}}});
 let latest;
 function render(s){latest=s;const m=s.agent.mind,w=m.workspace,t=m.last_trace,a=s.autonomy||{},run=a.status||{},paused=s.mind_control?.paused;
  $('mindMessage').placeholder='Message '+s.agent.name+'…';if(document.querySelector('.mind[data-pane="conversation"].active'))$('viewTitle').textContent=s.agent.name;
  if(w){$('studioFocusMini').textContent=w.focus.title;$('studioFlowMini').textContent=human(w.focus.kind)+' · '+w.retrieved.length+' memories in context · inspect the loop';}
  $('studioRunState').textContent=paused?'Paused · you can still talk':run.blocked?'Reconciling the previous attempt':['failed','recovering'].includes(run.state)?'Recovering · next thought scheduled':s.cognition_lease?'A thought is in progress':a.enabled?'Thinking between visits':'Think when you choose';
  $('studioRunDetail').textContent=run.blocked?'The previous attempt is being reconciled. Its evidence is retained; the scheduler will resume with a fresh episode after recovery.':paused?'Resume autonomous thought below when ready.':a.enabled?'The server checks every 15 minutes; the configured interval is '+a.interval_minutes+' minutes. '+(a.next_eligible_at?'Next eligible after '+new Date(a.next_eligible_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})+'.':'The next eligible check may start a cycle.'):'Use Think one cycle or a short exploration. Enable AUTONOMY_ENABLED in Netlify to continue while the page is closed.';
  $('studioBudget').textContent=(a.used_today||0)+' / '+(a.daily_limit||24);$('studioBudgetMeter').max=a.daily_limit||24;$('studioBudgetMeter').value=a.used_today||0;$('studioRecoverWorker').hidden=!run.blocked||!!s.cognition_lease;
  $('studioSelection').textContent=!w?'No selection yet':t?.broadcast?.selected_by==='operator_priority'?'Your message took priority':'Competitive attention';$('studioBroadcastFocus').textContent=w?.focus.title||'Run a thought cycle to populate the trace.';
  const bids=w?[w.focus,...w.competitors]:[],max=Math.max(1,...bids.map(b=>Math.abs(b.score)));$('studioBids').replaceChildren();
  for(const b of bids){const row=el('details','studio-bid'),sum=el('summary');sum.append(el('span',null,human(b.kind)+(b.id===w.focus.id?' · selected':'')),el('b',null,b.score.toFixed(2)));const bar=el('span','studio-bid-track'),fill=el('i');fill.style.width=Math.min(100,100*Math.abs(b.score)/max)+'%';fill.dataset.negative=String(b.score<0);bar.append(fill);sum.append(bar);row.append(sum,el('p',null,b.title));const values=el('dl','studio-contributions');for(const [k,v] of Object.entries(b.components||{}))values.append(el('dt',null,human(k)),el('dd',null,(v>=0?'+':'')+v.toFixed(3)));row.append(values);$('studioBids').append(row);}
  for(const [id,value] of Object.entries({studioRetrieved:w?.retrieved.length||0,studioCited:t?.cited_memory_ids?.length||0,studioStanceCount:t?.broadcast?.stance_changes?.length||0,studioIntentionCount:t?.intention_changes?.length||0}))$(id).textContent=value;
  $('studioTraceNote').textContent=t?.quarantined?'Reply delivered; proposed state updates were held after validation.':t?'Cycle '+t.tick+' · '+human(t.mode)+'. Download cycle evidence for the full request and response.':'A saved trace appears after a completed cycle.';
  const beliefs=(s.agent.beliefs||[]).filter(b=>b.active!==false);$('studioPositionTotal').textContent=beliefs.length;$('studioStances').replaceChildren();
  for(const b of beliefs.slice().sort((a,b)=>(b.updated_at||'').localeCompare(a.updated_at||'')).slice(0,12)){const item=el('details','studio-position'),sum=el('summary');sum.append(el('span',null,b.proposition),el('span','studio-stance',human(b.stance)));item.append(sum,el('p','mind-muted','Confidence '+Math.round(100*(b.confidence||0))+'% · '+human(b.origin)));const reasons=el('ul');for(const r of b.reasons_for||[])reasons.append(el('li',null,r));item.append(reasons);const revisions=(b.history||[]).slice().reverse();if(!revisions.length)item.append(el('p','mind-muted','Inherited snapshot. Earlier revisions were not recorded by this version.'));for(const r of revisions.slice(0,8)){const step=el('article','studio-revision');step.append(el('b',null,(r.before?.stance?human(r.before.stance)+' → ':'Formed: ')+human(r.after.stance)),el('small',null,'Episode '+r.episode+' · '+human(r.provenance)),el('p',null,(r.after.reasons_for||[]).join(' ')||'No supporting reason recorded.'));item.append(step);}$('studioStances').append(item);}
  if(!beliefs.length)$('studioStances').append(el('p','mind-muted','No positions recorded yet. Ask a question, then inspect the reasons it keeps or revises.'));
 }
 $('studioRecoverWorker').onclick=async()=>{const b=$('studioRecoverWorker'),note=$('studioRecoveryNote');b.disabled=true;note.hidden=false;try{const r=await apiFetch('/api/mind/autonomy/recover',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nonce:latest?.autonomy?.status?.nonce})});const x=await r.json();if(!r.ok)throw Error(x.error);note.textContent='Recovered. The next scheduled check may start a new cycle; the old attempt was not repeated.';document.dispatchEvent(new Event('mind:refresh'));}catch(e){note.textContent=e.message;}finally{b.disabled=false;}};
 document.addEventListener('mind:snapshot',e=>render(e.detail));document.dispatchEvent(new Event('mind:refresh'));
});
