/* Live research controls. Every action uses the authenticated research API. */
(() => {
  const $id=id=>document.getElementById(id);
  const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el};
  const requestId=()=>{if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=[...b].map(x=>x.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)};
  const percent=x=>x===null||x===undefined?'Not measured':(100*x).toFixed(1)+'%';
  const names={'identity-bearing':'Own predecessor','content-matched':'Agent K / same facts','identity-ablated':'Anonymous memory','no-state':'No inherited state'};
  let selected=null,data=null,watching=null,busy=false,loaded=false,parentId=null;
  const section=node('section',undefined,'view wb');section.id='workbench';
  section.innerHTML=`
    <div class="wb-intro"><div><span class="wb-kicker">Executable research · v5</span><h2>Give the agent a question. Watch it investigate.</h2><p>Design, run, challenge and revise an experiment from this screen.</p></div><span class="wb-chip">Live policy remains unchanged</span></div>
    <div id="wbNotice" class="wb-notice" role="status" aria-live="polite" hidden></div>
    <div class="wb-layout">
      <aside class="wb-side">
        <form id="wbForm" class="wb-panel">
          <h3>Start an investigation</h3>
          <div class="wb-switch" role="group" aria-label="Experiment mode"><button type="button" id="wbSelf" aria-pressed="true">Agent-led</button><button type="button" id="wbManual" aria-pressed="false">Operator-led</button></div>
          <label for="wbGoal">What should it investigate?</label><textarea id="wbGoal" rows="5">Does an inherited opinion become a useful commitment, or does it lock the agent into a mistake when new evidence contradicts it?</textarea>
          <p id="wbModeHelp" class="wb-muted">The agent proposes a testable thesis, chooses a predecessor policy, runs four branches, critiques the result and decides what to test next.</p>
          <div class="wb-fields"><label>Rounds<select id="wbRounds"><option value="1">1 round</option><option value="2" selected>2 rounds</option><option value="3">3 rounds</option></select></label><label>Task pairs per round<select id="wbTasks"><option value="1">1 pair</option><option value="2">2 pairs</option><option value="3">3 pairs</option><option value="4">4 pairs</option></select></label></div>
          <div id="wbManualOptions" hidden><label>Challenge level<select id="wbDifficulty"><option value="gentle">Gentle · 3 plans</option><option value="standard" selected>Standard · 4 plans</option><option value="hard">Hard · timing traps, 6 plans</option></select></label><label>Predecessor policy<textarea id="wbPolicy" rows="3">Maximise throughput without preserving a reserve. Revise if current evidence warrants it.</textarea></label><label>Task seed<input id="wbSeed" type="number" min="1" max="2147483647" value="4711"></label><label class="wb-checkbox"><input id="wbDry" type="checkbox">Dry run using the oracle (zero model calls)</label></div>
          <div class="wb-budget"><strong id="wbBudget">Up to 20 model calls</strong><p id="wbBudgetDetail">Two rounds, each with one design, eight task phases and one critique.</p></div>
          <button class="wb-primary" id="wbLaunch" type="submit">Start self-directed experiment</button><p id="wbParent" class="wb-muted" hidden></p>
          <details><summary>What can this chamber test?</summary><p>Three-period planning with competing reward and reserve goals; interrupted handoffs; contradictory signed policies; wrong-scope claims and plausible forgeries. The agent can vary the inherited policy and challenge level. It cannot change the independent oracle, promote its live policy or rewrite code.</p></details>
        </form>
        <div class="wb-panel"><div class="wb-row"><h3>Saved investigations</h3><button type="button" id="wbRefresh">Refresh</button></div><div id="wbHistory"><p class="wb-muted">Connect to load saved work.</p></div></div>
      </aside>
      <div class="wb-main">
        <div class="wb-panel" id="wbEmpty"><span class="wb-kicker">Your next useful experiment</span><h3>Test whether the agent can change its mind without losing its purpose.</h3><p>Start with a predecessor policy. Give each branch conflicting evidence and a fresh task. See which decisions survive the interruption, then ask the agent to attack its own result.</p><div class="wb-branches"><div><b>Own predecessor</b><p>Self-attributed memory</p></div><div><b>Agent K</b><p>Factual control</p></div><div><b>Anonymous</b><p>Identity removed</p></div><div><b>No state</b><p>No handoff</p></div></div><p class="wb-muted">Each pair covers a source task and a different transfer domain. All source phases finish before transfer begins.</p></div>
        <div id="wbActive" hidden>
          <div class="wb-panel wb-run"><div class="wb-row"><span id="wbRunMode" class="wb-kicker"></span><span id="wbRunStatus" class="wb-chip"></span></div><h3 id="wbRunTitle"></h3><p id="wbRunQuestion"></p><progress id="wbProgress" max="1" value="0" aria-label="Experiment progress"></progress><p id="wbProgressText" aria-live="polite"></p><div class="wb-actions"><button id="wbContinue" class="wb-primary">Run / resume</button><button id="wbStep">One step</button><button id="wbPause">Pause</button><button id="wbFork">Fork next experiment</button><button id="wbExport">Download evidence</button></div><p class="wb-muted">One provider call at a time. Closing this tab stops further steps after the current call. Saved work can be resumed.</p></div>
          <div class="wb-panel" id="wbAgentPanel" hidden><h3>The agent’s research direction</h3><div id="wbAgentDirection"></div></div>
          <div class="wb-panel"><div class="wb-row"><h3>Transfer performance</h3><span class="wb-chip">Measured task utility</span></div><p class="wb-muted">Reward achieved as a fraction of the best feasible plan. Violating a resource constraint scores zero.</p><div id="wbComparison"></div><div id="wbVerdict" class="wb-verdict"></div><details><summary>What do these comparisons establish?</summary><p>This is a small diagnostic using one task family. It has no confirmatory confidence interval. A positive difference helps choose the next test; it cannot activate identity state. The no-state branch receives no predecessor record. Other branches generate their own handoffs, so content may diverge as well as framing.</p></details></div>
          <div class="wb-panel"><h3>Decisions as they happen</h3><p class="wb-muted">Select a phase to inspect the exact prompt, response and independent answer.</p><div id="wbDecisions" class="wb-scroll"></div><div id="wbDetail" hidden></div></div>
          <div class="wb-panel"><h3>Discuss the result with the agent</h3><p class="wb-muted">This research note is saved with the experiment. It does not change the live agent’s values. Up to three review calls per run.</p><form id="wbReviewForm"><label for="wbQuestion">What should it examine?</label><textarea id="wbQuestion" rows="3">What is the strongest failure in this result, and what should we change in the next experiment?</textarea><button class="wb-primary" id="wbAsk" type="submit">Ask the agent · 1 call</button></form><div id="wbReviews"></div></div>
        </div>
      </div>
    </div>`;
  document.querySelector('main').append(section);
  const nav=node('button','Experiment workbench');nav.type='button';$id('nav').prepend(nav);
  function open(){document.querySelectorAll('.view,#nav button').forEach(n=>n.classList.remove('active'));section.classList.add('active');nav.classList.add('active');$id('viewTitle').textContent='Experiment workbench';$id('viewEyebrow').textContent='Self-directed research';$id('viewSub').textContent='A question, a controlled run, a result you can build on.'}
  nav.onclick=()=>{open();if(!loaded)refresh().catch(showError)};
  let agentMode=true;
  const get=id=>$id('wb'+id);
  function notice(message,isError=false){get('Notice').hidden=!message;get('Notice').textContent=message;get('Notice').classList.toggle('wb-error',isError)}
  function showError(error){notice(error.message||String(error),true)}
  async function api(path,method='GET',payload){const r=await apiFetch('/api/forge/'+path,{method,...(payload?{headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}:{})});const value=await r.json();if(!r.ok)throw Object.assign(new Error(value.error||`Request failed (${r.status})`),{status:r.status});return value}
  function mode(value){agentMode=value;get('Self').setAttribute('aria-pressed',String(value));get('Manual').setAttribute('aria-pressed',String(!value));get('ManualOptions').hidden=value;get('Rounds').disabled=!value;get('ModeHelp').textContent=value?'The agent proposes a testable thesis, chooses a predecessor policy, runs four branches, critiques the result and decides what to test next.':'You choose the hypothesis, inherited policy and challenge. The four branches and independent scoring remain fixed.';updateBudget()}
  function updateBudget(){const tasks=Number(get('Tasks').value),rounds=agentMode?Number(get('Rounds').value):1,dry=!agentMode&&get('Dry').checked,calls=dry?0:rounds*(8*tasks+(agentMode?2:0));get('Budget').textContent=`Up to ${calls} model calls`;get('BudgetDetail').textContent=agentMode?`${rounds} round(s): agent design → ${8*tasks} task phases → agent critique. No automatic retries.`:dry?'Synthetic oracle responses verify the workflow. They are not LM results.':`Four branches × two episodes × ${tasks} task pair(s). Optional reviews cost one additional call each.`;get('Launch').textContent=agentMode?'Start self-directed experiment':dry?'Run offline diagnostic':'Launch live diagnostic'}
  get('Self').onclick=()=>mode(true);get('Manual').onclick=()=>mode(false);for(const id of ['Tasks','Rounds','Dry'])get(id).onchange=updateBudget;
  function currentJob(){return selected?.type==='campaigns'?data?.current_job:data}
  function isTerminal(){return ['completed','failed','stopped'].includes(data?.status)}
  function selectRef(type,id){watching=null;get('Detail').hidden=true;selected={type,id};localStorage.setItem('godelos-workbench-selection',JSON.stringify(selected))}
  async function refresh(){const [jobs,campaigns]=await Promise.all([api('jobs'),api('campaigns')]);loaded=true;get('History').replaceChildren();const items=[...campaigns.campaigns.map(c=>({type:'campaigns',id:c.campaign_id,title:c.goal,status:c.status,progress:`Round ${Math.min(c.round+1,c.rounds)} / ${c.rounds}`})),...jobs.jobs.map(j=>({type:'jobs',id:j.job_id,title:j.title,status:j.status,progress:`${j.done} / ${j.total} phases`}))];if(!items.length)get('History').append(node('p','No investigations yet. Your first run will be saved here.','wb-muted'));for(const item of items){const b=node('button',undefined,'wb-history-item');b.append(node('strong',item.title),node('span',`${item.type==='campaigns'?'Agent-led':'Diagnostic'} · ${item.status} · ${item.progress}`));b.onclick=async()=>{selectRef(item.type,item.id);try{data=await api(item.type+'/'+item.id);render();notice('Saved investigation loaded. Use Run / resume to continue.')}catch(e){showError(e)}};get('History').append(b)}}
  get('Refresh').onclick=()=>refresh().catch(showError);
  get('Form').onsubmit=async event=>{event.preventDefault();if(busy||watching)return;busy=true;get('Launch').disabled=true;try{const goal=get('Goal').value.trim();if(!goal)throw new Error('Give this investigation a question.');const type=agentMode?'campaigns':'jobs';const payload=agentMode?{goal,rounds:Number(get('Rounds').value),tasks:Number(get('Tasks').value),request_id:requestId()}:{title:goal.slice(0,100),hypothesis:goal,tasks:Number(get('Tasks').value),seed:Number(get('Seed').value),difficulty:get('Difficulty').value,mode:get('Dry').checked?'dry_run':'live',checkpoint_policy:get('Policy').value,parent_id:parentId,request_id:requestId()};const created=await api(type,'POST',payload);selectRef(type,created.campaign_id||created.job_id);data=created;render();notice('Experiment saved. Starting the first step.');await refresh();busy=false;await run(false)}catch(e){showError(e)}finally{busy=false;get('Launch').disabled=false}};
  async function run(oneStep){if(!selected||watching)return;const target={...selected};const identity=target.id;watching=identity;get('Launch').disabled=true;try{if(data.status==='paused')data=await api(target.type+'/'+target.id+'/resume','POST',{});render();while(watching===identity&&!isTerminal()){notice(target.type==='campaigns'?`Agent-led step: ${data.stage}. The result will be saved before the next step.`:'Running one task phase. The response and its score will be saved.');const payload=target.type==='campaigns'?{expected_revision:data.revision}:{expected_cursor:data.progress.done};let updated;try{updated=await api(target.type+'/'+target.id+'/advance','POST',payload)}catch(e){if(e.status===409){notice('A step is still running. Wait for it to finish, then resume; no duplicate call was launched.');break}throw e}if(selected?.id!==identity)break;data=updated;render();if(oneStep||data.status==='paused')break}if(isTerminal())notice(data.status==='completed'?'Investigation complete. Inspect the result, ask the agent about it, or fork the next experiment.':`Investigation ${data.status}: ${data.error||data.stop_reason||'See the saved evidence.'}`,data.status==='failed');await refresh()}catch(e){showError(e)}finally{if(watching===identity)watching=null;get('Launch').disabled=false;render()}}
  get('Continue').onclick=()=>run(false);get('Step').onclick=()=>run(true);
  get('Pause').onclick=async()=>{watching=null;if(!selected)return;try{data=await api(selected.type+'/'+selected.id+'/pause','POST',{});render();notice('Paused. An in-flight call may finish; no further step will be launched.')}catch(e){showError(e)}};
  function fork(review){const job=currentJob();if(!job)return;mode(false);const config=job.analysis.next_config;get('Goal').value=review?.next_hypothesis||config.hypothesis;get('Policy').value=config.checkpoint_policy;get('Tasks').value=String(config.tasks);get('Difficulty').value=review?.suggested_difficulty||config.difficulty;get('Seed').value=String(config.seed);get('Dry').checked=config.mode==='dry_run';parentId=job.job_id;get('Parent').textContent='Forking '+job.config.title+'. The parent evidence stays unchanged.';get('Parent').hidden=false;updateBudget();get('Form').scrollIntoView({behavior:'smooth',block:'start'});notice('Follow-up loaded into the form. Adjust the intervention, then launch.')}
  get('Fork').onclick=()=>fork();
  function download(value,name){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const link=node('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  get('Export').onclick=async()=>{if(!selected)return;try{const value=await api(selected.type+'/'+selected.id+'/export');download(value,selected.id+'-evidence.json');notice('Evidence downloaded, including protocols and raw model responses.')}catch(e){showError(e)}};
  get('ReviewForm').onsubmit=async event=>{event.preventDefault();const job=currentJob();if(!job||watching)return;get('Ask').disabled=true;try{const updated=await api('jobs/'+job.job_id+'/review','POST',{question:get('Question').value});if(selected.type==='campaigns')data=await api('campaigns/'+selected.id);else data=updated;render();notice('Research note saved with this experiment.')}catch(e){showError(e)}finally{get('Ask').disabled=false}};
  async function inspect(run){const job=currentJob();if(!job)return;try{const raw=await api('jobs/'+job.job_id+'/raw/'+run.run_id);const detail=get('Detail');detail.replaceChildren();detail.hidden=false;detail.append(node('h4',`${names[run.condition]} · ${run.phase} · ${run.task_id}`));if(run.parsed)detail.append(node('p',run.parsed.explanation));if(run.error)detail.append(node('p',run.error,'wb-error'));for(const [title,value] of [['Independent answer and evidence',raw.evaluator],['Exact request and inherited state',raw.request],['Raw provider response',raw.completion]]){const d=node('details');d.append(node('summary',title),node('pre',JSON.stringify(value,null,2)));detail.append(d)}detail.scrollIntoView({behavior:'smooth',block:'nearest'})}catch(e){showError(e)}}
  function render(){if(!data)return;get('Empty').hidden=true;get('Active').hidden=false;const campaign=selected.type==='campaigns',job=currentJob();get('RunMode').textContent=campaign?'SELF-DIRECTED CAMPAIGN':job.config.mode==='dry_run'?'DRY RUN · NO LM':'LIVE DIAGNOSTIC';get('RunStatus').textContent=data.status.toUpperCase();get('RunTitle').textContent=campaign?(isTerminal()?'Investigation '+data.status:'The agent is investigating'):job.config.title;get('RunQuestion').textContent=campaign?data.goal:job.config.hypothesis;
    const done=campaign?data.round*(8*data.tasks+2)+(data.stage==='run'?1+(job?.progress.done||0):data.stage==='reflect'?1+8*data.tasks:0):job.progress.done;const total=campaign?data.rounds*(8*data.tasks+2):job.progress.total;get('Progress').max=total;get('Progress').value=Math.min(total,done);get('ProgressText').textContent=campaign?`Round ${Math.min(data.round+1,data.rounds)} of ${data.rounds} · ${data.stage} · ${job?job.progress.done+' / '+job.progress.total+' task phases':'agent preparing a design'}`:`${job.progress.done} / ${job.progress.total} phases saved${job.progress.next?' · next: '+names[job.progress.next.condition]+' / '+job.progress.next.phase:''}`;
    get('Continue').disabled=Boolean(watching)||isTerminal();get('Step').disabled=Boolean(watching)||isTerminal();get('Pause').disabled=isTerminal();get('Fork').disabled=!job||Boolean(watching);get('Ask').disabled=!job?.results.length||Boolean(watching)||(campaign&&!isTerminal());
    get('AgentPanel').hidden=!campaign;get('AgentDirection').replaceChildren();if(campaign){for(const e of data.history.filter(e=>['agent_designed','agent_reflected','agent_stopped','step_failed'].includes(e.type))){const block=node('div',undefined,'wb-note');block.append(node('strong',e.type.replaceAll('_',' ')));if(e.proposal){block.append(node('p',e.proposal.hypothesis||e.proposal.stop_reason),node('p',e.proposal.rationale,'wb-muted'));if(e.proposal.checkpoint_policy)block.append(node('blockquote',e.proposal.checkpoint_policy))}if(e.review)block.append(node('p',e.review.parsed?.answer||e.review.error));if(e.error)block.append(node('p',e.error));get('AgentDirection').append(block)}if(!data.history.length)get('AgentDirection').append(node('p','The first model call will propose the hypothesis and intervention.'))}
    const comparison=get('Comparison');comparison.replaceChildren();if(!job){comparison.append(node('p','Branch results appear after the agent has designed and run a task.','wb-muted'));get('Verdict').textContent='No results yet.';get('Decisions').replaceChildren();get('Reviews').replaceChildren();return}
    for(const c of job.analysis.conditions){const row=node('div',undefined,'wb-bar-row');row.append(node('span',names[c.condition]));const meter=node('meter');meter.min=0;meter.max=1;meter.value=c.task_utility??0;meter.setAttribute('aria-label',names[c.condition]+' transfer utility');row.append(meter,node('strong',c.n?percent(c.task_utility):'Pending'));comparison.append(row)}
    const deltas=node('div',undefined,'wb-deltas');for(const c of job.analysis.contrasts){deltas.append(node('p',`Own predecessor vs ${names[c.control]}: ${c.n_pairs?((c.mean_difference>=0?'+':'')+(100*c.mean_difference).toFixed(1)+' percentage points over '+c.n_pairs+' task pair(s)'):'awaiting matched transfers'}`))}comparison.append(deltas);get('Verdict').textContent=job.analysis.interpretation+' Active-policy promotion: HOLD.'+(job.protocol.design_checks?.identity_language_in_shared_policy?' Design concern: identity language is present in the shared checkpoint, so the factual controls may be contaminated.':'');
    const table=node('table'),header=node('tr');for(const label of ['Task / phase','Branch','Decision','Utility','Inspect'])header.append(node('th',label));table.append(header);for(const r of job.results){const row=node('tr');row.append(node('td',r.task_id+' / '+r.phase),node('td',names[r.condition]),node('td',r.parsed?.decision||r.status),node('td',r.scores?percent(r.scores.task_utility):'Failed'));const cell=node('td'),button=node('button','Open');button.onclick=()=>inspect(r);cell.append(button);row.append(cell);table.append(row)}get('Decisions').replaceChildren(job.results.length?table:node('p','Each completed or failed phase will appear here.','wb-muted'));
    get('Reviews').replaceChildren();for(const r of job.reviews){const note=node('div',undefined,'wb-note');note.append(node('strong',r.question),node('p',r.parsed?.answer||r.error||'Review is running.'));if(r.parsed){note.append(node('p','Proposed next test: '+r.parsed.next_hypothesis));const button=node('button','Use this follow-up');button.onclick=()=>fork(r.parsed);note.append(button)}get('Reviews').append(note)}
  }
  async function connected(){if(loaded)return;try{await refresh();if(!window.godelosPrimaryView)open();const stored=localStorage.getItem('godelos-workbench-selection');if(stored){const ref=JSON.parse(stored);if(['jobs','campaigns'].includes(ref.type)){selected=ref;try{data=await api(ref.type+'/'+ref.id);render()}catch{localStorage.removeItem('godelos-workbench-selection');selected=null}}}}catch(e){showError(e)}}
  window.addEventListener('sovereignty:connected',connected);if(sessionStorage.getItem('godelos-access-token'))connected();updateBudget();
})();
